---

### Ansible / Ansistrano
domain: 'drupalcamp.es'
domain_env: "{{ ( '2020.' if appenv == 'pro' else appenv + '.' ) + domain }}"

### Deploy
rsync_extra_params:
  - '--exclude=web/sites/default/settings.local.php'

drupal_rel_path : '/web'
drush_args : ''
varnish_domain : "{{ 'dummy' if appenv != 'pro' else 'drupalcamp.es' }}"
varnish_servers :
  - '127.0.0.1:6081'
### Reload db
drush_sanitize_mail: 'drupalcamp+user_%uid@drupal.es'

### Reload files
public_files_dir: 'web/sites/default/files'

# Shared
shared_dirs:
  web/sites/default/files: "{{ shared_dir }}"
  web/sites/default/private: "{{ shared_dir }}"

shared_files:
  web/sites/default/settings.local.php: "{{ shared_file }}"

