---

### Ansible / Ansistrano
domain: 'drupalday.es'
domain_env: "{{ ( '2019.' if appenv == 'pro' else appenv + '.' ) + domain }}"
docroot: 'current/web'

### Deploy
rsync_extra_params:
  - '--exclude=sites/default/settings.local.php'

### Reload db
drush_sanitize_mail: 'drupalday+user_%uid@drupal.es'

# Shared
shared_dirs:
  sites/default/files: "{{ shared_dir }}"
  sites/default/private: "{{ shared_dir }}"

shared_files:
  sites/default/settings.local.php: "{{ shared_file }}"

