---

ansistrano_shared_paths:
  - 'sites/default/files'
  - 'sites/default/private'
ansistrano_shared_files:
  - 'sites/default/settings.php'

rsync_extra_params:
  - '--exclude=web/sites/default/settings.local.php'

drupal_rel_path : '/web'
drush_args : ''
varnish_domain : 'drupalday.es'
varnish_servers :
  - '127.0.0.1:6081'
