---

domain: 'drupalday.es'
domain_env: "{{ ('2017.' if appenv == 'pro' else '.' + appenv ) + domain }}"

pipelines:
  deploy-ENV:
    config:
      jobFolder: ''
      ansible:
        extra_files:
          - 'ansible/tasks/drush-cc-all.yml'
    vars:
      repo:
        url: 'git@github.com:AsociacionDrupalES/DrupalDay.git'
        credentials_id: '20552984-a646-4dfc-b94a-59f26887fd59'
      deploy:
        credentials_id: '02304973-08cf-4390-8edb-7a5c9d940cb8'
    variants:
      deploy-ENV:
        vars:
          environments: '#!groovy config._envs_dev'
      PROD-deploy:
        vars:
          environments: '#!groovy config._envs_pro'

