---

domain: 'drupalday.es'

files:
  ansible/dday/extra-vars.yml:
    path: 'ansible/extra-vars.yml'

ansible:
  extra_vars:
    - 'ansible/extra-vars.yml'
    - 'ansible/dday/extra-vars.yml'

pipelines:
  deploy-ENV:
    config:
      jobFolder: ''
    vars:
      repo:
        url: 'git@github.com:AsociacionDrupalES/DrupalDay.git'
        credentials_id: '20552984-a646-4dfc-b94a-59f26887fd59'
      deploy:
        credentials_id: '02304973-08cf-4390-8edb-7a5c9d940cb8'
    variants:
      deploy-ENV:
        vars:
          environments: '#!groovy config._envs_dev'
      PROD-deploy:
        vars:
          environments: '#!groovy config._envs_pro'

